device: cuda:0
num_classes: 37
batch_size: 32
max_num_epochs: 20
patience: 5
adam_optimizer_config:
  lr: 0.001
  weight_decay: 0.001
num_batch_norm_layers_to_train_params: 0
num_batch_norm_layers_to_update_running_stats: 0