device: cuda:0
num_classes: 37
batch_size: 32
max_num_epochs: 20
patience: 5
adam_optimizer_config:
  lr: 0.001
  weight_decay: 0.001
num_batch_norm_layers_to_train_params: 0
num_batch_norm_layers_to_update_running_stats: 0
train_earlier_layers_delay: 5
n_hidden_layers_to_train: 20
# Parameters for the pseudo label learning
use_pseudo_labelling: 1
labelled_data_ratio: 0.1
T_1: 20
T_2: 8
ALPHA_F: 3
unlabelled_batch_size: 48